spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=novadesk-secret-key-change-this-in-production-very-long-key
jwt.expiration=86400000